// This file intentionally uses JavaScript-compatible TypeScript so it can run
// directly on Node 22 or be copied to main.js for older Node versions.
"use strict";
const fs = require("node:fs");
const os = require("node:os");
const { Worker, isMainThread, parentPort, workerData } = require("node:worker_threads");

const YEAR_START = 1798761600;
const MONTH_START = [1798761600,1801440000,1803859200,1806537600,1809129600,1811808000,1814400000,1817078400,1819756800,1822348800,1825027200,1827619200,1830297600];
const MONTH_LABEL = ["2027-01","2027-02","2027-03","2027-04","2027-05","2027-06","2027-07","2027-08","2027-09","2027-10","2027-11","2027-12"];
const MONTH_BY_DAY = new Uint8Array(365);
for (let d=0,m=0;d<365;d++){const ts=YEAR_START+d*86400;if(ts>=MONTH_START[m+1])m++;MONTH_BY_DAY[d]=m;}

function timestamp10(line){let x=line.charCodeAt(0)-48;for(let i=1;i<10;i++)x=x*10+line.charCodeAt(i)-48;return x;}
function parseArgs(args){if(args.length===2&&!args[0].startsWith("-")&&!args[1].startsWith("-"))return{input:args[0],output:args[1],threads:os.cpus().length,profile:false};const o={input:"",output:"",threads:os.cpus().length,profile:false};for(let i=0;i<args.length;i++){switch(args[i]){case"-i":case"--input":o.input=args[++i];break;case"-o":case"--output":o.output=args[++i];break;case"-t":case"--threads":o.threads=Number(args[++i]);break;case"--profile":o.profile=true;break;default:throw new Error(`unknown argument: ${args[i]}`);}}if(!o.input||!Number.isInteger(o.threads)||o.threads<1)throw new Error("optimized TypeScript analyzer requires -i and positive -t");return o;}
function makeStore(){return {ids:new Map(),keys:[],stats:new Float64Array(1024*60),size:0};}
function ensure(store){if(store.size*60<store.stats.length)return;const next=new Float64Array(store.stats.length*2);next.set(store.stats);store.stats=next;}
function processLine(line,store){if(!line)return;const ts=timestamp10(line);const month=MONTH_BY_DAY[Math.floor((ts-YEAR_START)/86400)];const c1=line.indexOf(",",11),c2=line.indexOf(",",c1+1);const channel=line.slice(11,c1);let id=store.ids.get(channel);if(id===undefined){id=store.size++;ensure(store);store.ids.set(channel,id);store.keys.push(channel);}const ml=Number(line.slice(c1+1,c2)),stamps=Number(line.slice(c2+1));const p=id*60+month*5,st=store.stats;if(st[p+3]===0){st[p]=ml;st[p+1]=ml;st[p+2]=ml;st[p+3]=1;st[p+4]=stamps;}else{if(ml<st[p])st[p]=ml;if(ml>st[p+2])st[p+2]=ml;st[p+1]+=ml;st[p+3]++;st[p+4]+=stamps;}}
function analyzeRange(path,begin,end){const started=process.hrtime.bigint(),store=makeStore(),fd=fs.openSync(path,"r"),buffer=Buffer.allocUnsafe(8<<20);let pos=begin,carry="";while(pos<end){const want=Math.min(buffer.length,end-pos),n=fs.readSync(fd,buffer,0,want,pos);if(n===0)break;pos+=n;const parts=(carry+buffer.toString("ascii",0,n)).split("\n");carry=parts.pop();for(const line of parts)processLine(line,store);}if(carry)processLine(carry,store);fs.closeSync(fd);const out=store.stats.buffer.slice(0,store.size*60*8);return {keys:store.keys,buffer:out,elapsed:Number(process.hrtime.bigint()-started)/1e9};}
function mergeResult(all,result){const src=new Float64Array(result.buffer);for(let i=0;i<result.keys.length;i++){const key=result.keys[i];let id=all.ids.get(key);if(id===undefined){id=all.size++;ensure(all);all.ids.set(key,id);all.keys.push(key);}const si=i*60,di=id*60;for(let m=0;m<12;m++){const sp=si+m*5,dp=di+m*5;if(src[sp+3]===0)continue;if(all.stats[dp+3]===0){for(let j=0;j<5;j++)all.stats[dp+j]=src[sp+j];}else{if(src[sp]<all.stats[dp])all.stats[dp]=src[sp];if(src[sp+2]>all.stats[dp+2])all.stats[dp+2]=src[sp+2];all.stats[dp+1]+=src[sp+1];all.stats[dp+3]+=src[sp+3];all.stats[dp+4]+=src[sp+4];}}}}
function formatFixed2(value){const buffer=new ArrayBuffer(8),view=new DataView(buffer);view.setFloat64(0,value,false);const bits=view.getBigUint64(0,false),eb=Number((bits>>52n)&0x7ffn),fraction=bits&((1n<<52n)-1n);let mantissa,exponent;if(eb===0){mantissa=fraction;exponent=-1074;}else{mantissa=(1n<<52n)|fraction;exponent=eb-1075;}const scaled=mantissa*100n;let cents;if(exponent>=0)cents=scaled<<BigInt(exponent);else{const denominator=1n<<BigInt(-exponent);cents=scaled/denominator;const remainder=scaled%denominator,twice=remainder*2n;if(twice>denominator||(twice===denominator&&cents%2n===1n))cents++;}return `${cents/100n}.${(cents%100n).toString().padStart(2,"0")}`;}
function writeResult(path,all){const fd=path?fs.openSync(path,"w"):1;const order=Array.from({length:all.size},(_,i)=>i).sort((a,b)=>all.keys[a]<all.keys[b]?-1:all.keys[a]>all.keys[b]?1:0);let output="";for(const id of order)for(let m=0;m<12;m++){const p=id*60+m*5,s=all.stats;if(s[p+3]===0)continue;output+=`${all.keys[id]},${MONTH_LABEL[m]}=${s[p]}/${formatFixed2(s[p+1]/s[p+3])}/${s[p+2]}/${s[p+3]}/${s[p+4]}\n`;if(output.length>=(4<<20)){fs.writeSync(fd,output);output="";}}if(output)fs.writeSync(fd,output);if(path)fs.closeSync(fd);}
function findNewline(fd,pos,end){const b=Buffer.allocUnsafe(1<<20);while(pos<end){const n=fs.readSync(fd,b,0,Math.min(b.length,end-pos),pos),at=b.indexOf(10,0);if(at>=0)return pos+at+1;if(!n)break;pos+=n;}return end;}

async function main(){const total=process.hrtime.bigint(),o=parseArgs(process.argv.slice(2)),header=Buffer.from("unix_timestamp,channel_path,message_length,stamp_count\n"),fd=fs.openSync(o.input,"r"),stat=fs.fstatSync(fd),check=Buffer.alloc(header.length);fs.readSync(fd,check,0,check.length,0);if(!check.equals(header))throw new Error("unsupported CSV header");const ranges=[],begin=header.length;let start=begin;for(let i=0;i<o.threads;i++){const stop=i+1===o.threads?stat.size:findNewline(fd,begin+Math.floor((stat.size-begin)*(i+1)/o.threads),stat.size);ranges.push([start,stop]);start=stop;}fs.closeSync(fd);const workerStart=process.hrtime.bigint();const results=await Promise.all(ranges.map(([a,b])=>new Promise((resolve,reject)=>{const w=new Worker(__filename,{workerData:{path:o.input,begin:a,end:b}});w.once("message",resolve);w.once("error",reject);w.once("exit",code=>{if(code)reject(new Error(`worker exited ${code}`));});})));const workerWall=Number(process.hrtime.bigint()-workerStart)/1e9,mergeStart=process.hrtime.bigint(),merged=makeStore();for(const r of results)mergeResult(merged,r);const merge=Number(process.hrtime.bigint()-mergeStart)/1e9,outputStart=process.hrtime.bigint();writeResult(o.output,merged);const outputTime=Number(process.hrtime.bigint()-outputStart)/1e9;if(o.profile){let groups=0;for(let i=0;i<merged.size*60;i+=5)if(merged.stats[i+3])groups++;console.error(`profile workers_wall=${workerWall.toFixed(6)} workers_sum=${results.reduce((n,r)=>n+r.elapsed,0).toFixed(6)} merge=${merge.toFixed(6)} output=${outputTime.toFixed(6)} total=${(Number(process.hrtime.bigint()-total)/1e9).toFixed(6)} chunks=${o.threads} groups=${groups}`);}}
if(isMainThread)main().catch(e=>{console.error(e.message||String(e));process.exit(1);});else{const result=analyzeRange(workerData.path,workerData.begin,workerData.end);parentPort.postMessage(result,[result.buffer]);}
