// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthUserMethod.
const (
	Header AuthUserMethod = "header"
	Token  AuthUserMethod = "token"
)

// Valid indicates whether the value is a known member of the AuthUserMethod enum.
func (e AuthUserMethod) Valid() bool {
	switch e {
	case Header:
		return true
	case Token:
		return true
	default:
		return false
	}
}

// Defines values for DatasetKind.
const (
	Expected DatasetKind = "expected"
	Input    DatasetKind = "input"
)

// Valid indicates whether the value is a known member of the DatasetKind enum.
func (e DatasetKind) Valid() bool {
	switch e {
	case Expected:
		return true
	case Input:
		return true
	default:
		return false
	}
}

// Defines values for DatasetManifestSchemaVersion.
const (
	N1 DatasetManifestSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the DatasetManifestSchemaVersion enum.
func (e DatasetManifestSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionKind.
const (
	ExecutionKindBun        ExecutionKind = "bun"
	ExecutionKindJavascript ExecutionKind = "javascript"
	ExecutionKindNative     ExecutionKind = "native"
	ExecutionKindRuby       ExecutionKind = "ruby"
	ExecutionKindTypescript ExecutionKind = "typescript"
)

// Valid indicates whether the value is a known member of the ExecutionKind enum.
func (e ExecutionKind) Valid() bool {
	switch e {
	case ExecutionKindBun:
		return true
	case ExecutionKindJavascript:
		return true
	case ExecutionKindNative:
		return true
	case ExecutionKindRuby:
		return true
	case ExecutionKindTypescript:
		return true
	default:
		return false
	}
}

// Defines values for Language.
const (
	LanguageBun        Language = "bun"
	LanguageC          Language = "c"
	LanguageCpp        Language = "cpp"
	LanguageCsharp     Language = "csharp"
	LanguageGo         Language = "go"
	LanguageJavascript Language = "javascript"
	LanguageOther      Language = "other"
	LanguageRuby       Language = "ruby"
	LanguageRust       Language = "rust"
	LanguageTypescript Language = "typescript"
	LanguageZig        Language = "zig"
)

// Valid indicates whether the value is a known member of the Language enum.
func (e Language) Valid() bool {
	switch e {
	case LanguageBun:
		return true
	case LanguageC:
		return true
	case LanguageCpp:
		return true
	case LanguageCsharp:
		return true
	case LanguageGo:
		return true
	case LanguageJavascript:
		return true
	case LanguageOther:
		return true
	case LanguageRuby:
		return true
	case LanguageRust:
		return true
	case LanguageTypescript:
		return true
	case LanguageZig:
		return true
	default:
		return false
	}
}

// Defines values for LeaderboardBoard.
const (
	Private LeaderboardBoard = "private"
	Public  LeaderboardBoard = "public"
)

// Valid indicates whether the value is a known member of the LeaderboardBoard enum.
func (e LeaderboardBoard) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for SubmissionAcceptedStatus.
const (
	SubmissionAcceptedStatusQueued SubmissionAcceptedStatus = "queued"
)

// Valid indicates whether the value is a known member of the SubmissionAcceptedStatus enum.
func (e SubmissionAcceptedStatus) Valid() bool {
	switch e {
	case SubmissionAcceptedStatusQueued:
		return true
	default:
		return false
	}
}

// Defines values for SubmissionStatus.
const (
	SubmissionStatusCompleted           SubmissionStatus = "completed"
	SubmissionStatusDisqualified        SubmissionStatus = "disqualified"
	SubmissionStatusInfrastructureError SubmissionStatus = "infrastructure_error"
	SubmissionStatusQueued              SubmissionStatus = "queued"
	SubmissionStatusRejected            SubmissionStatus = "rejected"
	SubmissionStatusRunning             SubmissionStatus = "running"
	SubmissionStatusUploading           SubmissionStatus = "uploading"
)

// Valid indicates whether the value is a known member of the SubmissionStatus enum.
func (e SubmissionStatus) Valid() bool {
	switch e {
	case SubmissionStatusCompleted:
		return true
	case SubmissionStatusDisqualified:
		return true
	case SubmissionStatusInfrastructureError:
		return true
	case SubmissionStatusQueued:
		return true
	case SubmissionStatusRejected:
		return true
	case SubmissionStatusRunning:
		return true
	case SubmissionStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for Verdict.
const (
	Accepted            Verdict = "accepted"
	Disqualified        Verdict = "disqualified"
	InfrastructureError Verdict = "infrastructure_error"
	InvalidSubmission   Verdict = "invalid_submission"
	OutputLimit         Verdict = "output_limit"
	RuntimeError        Verdict = "runtime_error"
	TimeLimit           Verdict = "time_limit"
	WrongAnswer         Verdict = "wrong_answer"
)

// Valid indicates whether the value is a known member of the Verdict enum.
func (e Verdict) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Disqualified:
		return true
	case InfrastructureError:
		return true
	case InvalidSubmission:
		return true
	case OutputLimit:
		return true
	case RuntimeError:
		return true
	case TimeLimit:
		return true
	case WrongAnswer:
		return true
	default:
		return false
	}
}

// Defines values for PublishPrivate200JSONResponseBodyPublished.
const (
	True PublishPrivate200JSONResponseBodyPublished = true
)

// Valid indicates whether the value is a known member of the PublishPrivate200JSONResponseBodyPublished enum.
func (e PublishPrivate200JSONResponseBodyPublished) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for UnpublishPrivate200JSONResponseBodyPublished.
const (
	False UnpublishPrivate200JSONResponseBodyPublished = false
)

// Valid indicates whether the value is a known member of the UnpublishPrivate200JSONResponseBodyPublished enum.
func (e UnpublishPrivate200JSONResponseBodyPublished) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// AccessKeyResponse defines model for AccessKeyResponse.
type AccessKeyResponse struct {
	AccessKey string `json:"accessKey"`
	Prefix    string `json:"prefix"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	IsAdmin  bool           `json:"isAdmin"`
	Method   AuthUserMethod `json:"method"`
	Username string         `json:"username"`
}

// AuthUserMethod defines model for AuthUser.Method.
type AuthUserMethod string

// BenchmarkEnvironment defines model for BenchmarkEnvironment.
type BenchmarkEnvironment struct {
	Bun                     string   `json:"bun"`
	Cpu                     string   `json:"cpu"`
	Docker                  string   `json:"docker"`
	Id                      string   `json:"id"`
	InstanceType            string   `json:"instanceType"`
	Kernel                  string   `json:"kernel"`
	Memory                  string   `json:"memory"`
	Node                    string   `json:"node"`
	Os                      string   `json:"os"`
	OutputLimitBytes        int32    `json:"outputLimitBytes"`
	PidLimit                int32    `json:"pidLimit"`
	Repetitions             int32    `json:"repetitions"`
	Ruby                    string   `json:"ruby"`
	RunnerImage             string   `json:"runnerImage"`
	SharedLibraries         []string `json:"sharedLibraries"`
	SlowFirstAttemptSeconds int32    `json:"slowFirstAttemptSeconds"`
	StdioLimitBytes         int32    `json:"stdioLimitBytes"`
	TimeoutSeconds          int32    `json:"timeoutSeconds"`
}

// BenchmarkOutcome defines model for BenchmarkOutcome.
type BenchmarkOutcome struct {
	Error   *string      `json:"error"`
	ScoreNs *Nanoseconds `json:"scoreNs"`
	Verdict Verdict      `json:"verdict"`
}

// ContestLiveUpdate defines model for ContestLiveUpdate.
type ContestLiveUpdate struct {
	Contest struct {
		Participants       int32           `json:"participants"`
		PrivatePublishedAt *DateTimeString `json:"privatePublishedAt"`
		TotalSubmissions   int32           `json:"totalSubmissions"`
	} `json:"contest"`
	Leaderboard Leaderboard `json:"leaderboard"`
}

// ContestOverview defines model for ContestOverview.
type ContestOverview struct {
	EndAt              DateTimeString       `json:"endAt"`
	Environment        BenchmarkEnvironment `json:"environment"`
	Id                 string               `json:"id"`
	Name               string               `json:"name"`
	Participants       int32                `json:"participants"`
	PrivatePublishedAt *DateTimeString      `json:"privatePublishedAt"`
	StartAt            DateTimeString       `json:"startAt"`
	TotalSubmissions   int32                `json:"totalSubmissions"`
}

// DatasetArtifact defines model for DatasetArtifact.
type DatasetArtifact struct {
	CompressedBytes    int64       `json:"compressedBytes"`
	CompressedSha256   string      `json:"compressedSha256"`
	Id                 string      `json:"id"`
	IsPublic           bool        `json:"isPublic"`
	Kind               DatasetKind `json:"kind"`
	Label              string      `json:"label"`
	ObjectKey          string      `json:"objectKey"`
	Rows               int64       `json:"rows"`
	UncompressedBytes  int64       `json:"uncompressedBytes"`
	UncompressedSha256 string      `json:"uncompressedSha256"`
}

// DatasetKind defines model for DatasetKind.
type DatasetKind string

// DatasetManifest defines model for DatasetManifest.
type DatasetManifest struct {
	Artifacts         []DatasetArtifact            `json:"artifacts"`
	ContestId         string                       `json:"contestId"`
	GeneratedAt       DateTimeString               `json:"generatedAt"`
	GeneratorRevision string                       `json:"generatorRevision"`
	SchemaVersion     DatasetManifestSchemaVersion `json:"schemaVersion"`
}

// DatasetManifestSchemaVersion defines model for DatasetManifest.SchemaVersion.
type DatasetManifestSchemaVersion float32

// DatasetsResponse defines model for DatasetsResponse.
type DatasetsResponse struct {
	Datasets []PublicDataset `json:"datasets"`
}

// DateTimeString defines model for DateTimeString.
type DateTimeString = string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"requestId"`
}

// ExecutionKind defines model for ExecutionKind.
type ExecutionKind string

// Language defines model for Language.
type Language string

// Leaderboard defines model for Leaderboard.
type Leaderboard struct {
	Board            LeaderboardBoard   `json:"board"`
	Disqualified     []LeaderboardEntry `json:"disqualified"`
	PrivatePublished bool               `json:"privatePublished"`
	Ranked           []LeaderboardEntry `json:"ranked"`
}

// LeaderboardBoard defines model for LeaderboardBoard.
type LeaderboardBoard string

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	Language        Language       `json:"language"`
	Rank            *int32         `json:"rank"`
	RankChange      *int32         `json:"rankChange"`
	ScoreNs         *Nanoseconds   `json:"scoreNs"`
	SourceAvailable bool           `json:"sourceAvailable"`
	SubmissionId    Uuid           `json:"submissionId"`
	SubmittedAt     DateTimeString `json:"submittedAt"`
	Username        string         `json:"username"`
	Verdict         Verdict        `json:"verdict"`
}

// LeaderboardReplayResponse defines model for LeaderboardReplayResponse.
type LeaderboardReplayResponse struct {
	Submissions []LeaderboardReplaySubmission `json:"submissions"`
}

// LeaderboardReplaySubmission defines model for LeaderboardReplaySubmission.
type LeaderboardReplaySubmission struct {
	Disqualified   bool           `json:"disqualified"`
	Language       *Language      `json:"language"`
	PrivateScoreNs *Nanoseconds   `json:"privateScoreNs"`
	PrivateVerdict *Verdict       `json:"privateVerdict"`
	PublicVerdict  *Verdict       `json:"publicVerdict"`
	SubmissionId   Uuid           `json:"submissionId"`
	SubmittedAt    DateTimeString `json:"submittedAt"`
	Username       string         `json:"username"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	User *AuthUser `json:"user"`
}

// Nanoseconds defines model for Nanoseconds.
type Nanoseconds = string

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok bool `json:"ok"`
}

// PublicDataset defines model for PublicDataset.
type PublicDataset struct {
	CompressedBytes    string      `json:"compressedBytes"`
	CompressedSha256   string      `json:"compressedSha256"`
	DownloadUrl        string      `json:"downloadUrl"`
	Id                 string      `json:"id"`
	Kind               DatasetKind `json:"kind"`
	Label              string      `json:"label"`
	Rows               string      `json:"rows"`
	UncompressedBytes  string      `json:"uncompressedBytes"`
	UncompressedSha256 string      `json:"uncompressedSha256"`
}

// Submission defines model for Submission.
type Submission struct {
	ArtifactSha256      *string           `json:"artifactSha256"`
	CompletedAt         *DateTimeString   `json:"completedAt"`
	DisqualifiedReason  *string           `json:"disqualifiedReason"`
	ExecutionKind       *ExecutionKind    `json:"executionKind"`
	Id                  Uuid              `json:"id"`
	InfrastructureError *string           `json:"infrastructureError"`
	Language            *Language         `json:"language"`
	Private             *BenchmarkOutcome `json:"private,omitempty"`
	Public              *BenchmarkOutcome `json:"public"`
	QueueAhead          *int32            `json:"queueAhead"`
	QueuedAt            *DateTimeString   `json:"queuedAt"`
	SourceFilename      *string           `json:"sourceFilename"`
	StartedAt           *DateTimeString   `json:"startedAt"`
	Status              SubmissionStatus  `json:"status"`
	SubmissionNumber    *int32            `json:"submissionNumber"`
	UploadStartedAt     DateTimeString    `json:"uploadStartedAt"`
	Username            string            `json:"username"`
}

// SubmissionAccepted defines model for SubmissionAccepted.
type SubmissionAccepted struct {
	Id              Uuid                     `json:"id"`
	Status          SubmissionAcceptedStatus `json:"status"`
	StatusUrl       string                   `json:"statusUrl"`
	UploadStartedAt DateTimeString           `json:"uploadStartedAt"`
}

// SubmissionAcceptedStatus defines model for SubmissionAccepted.Status.
type SubmissionAcceptedStatus string

// SubmissionResponse defines model for SubmissionResponse.
type SubmissionResponse struct {
	Submission Submission `json:"submission"`
}

// SubmissionStatus defines model for SubmissionStatus.
type SubmissionStatus string

// SubmissionUpload defines model for SubmissionUpload.
type SubmissionUpload struct {
	Binary        *openapi_types.File `json:"binary,omitempty"`
	ExecutionKind ExecutionKind       `json:"executionKind"`
	Language      *Language           `json:"language,omitempty"`
	Source        openapi_types.File  `json:"source"`
}

// SubmissionsResponse defines model for SubmissionsResponse.
type SubmissionsResponse struct {
	Submissions []Submission `json:"submissions"`
}

// Uuid defines model for Uuid.
type Uuid = string

// Verdict defines model for Verdict.
type Verdict string

// PublishPrivate200JSONResponseBodyPublished defines parameters for PublishPrivate.
type PublishPrivate200JSONResponseBodyPublished bool

// UnpublishPrivate200JSONResponseBodyPublished defines parameters for UnpublishPrivate.
type UnpublishPrivate200JSONResponseBodyPublished bool

// DisqualifySubmissionJSONBody defines parameters for DisqualifySubmission.
type DisqualifySubmissionJSONBody struct {
	Reason string `json:"reason"`
}

// StreamContestParams defines parameters for StreamContest.
type StreamContestParams struct {
	Board    *LeaderboardBoard `form:"board,omitempty" json:"board,omitempty"`
	Language *Language         `form:"language,omitempty" json:"language,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	Board    *LeaderboardBoard `form:"board,omitempty" json:"board,omitempty"`
	Language *Language         `form:"language,omitempty" json:"language,omitempty"`
}

// ImportDatasetsJSONRequestBody defines body for ImportDatasets for application/json ContentType.
type ImportDatasetsJSONRequestBody = DatasetManifest

// DisqualifySubmissionJSONRequestBody defines body for DisqualifySubmission for application/json ContentType.
type DisqualifySubmissionJSONRequestBody DisqualifySubmissionJSONBody

// CreateSubmissionMultipartRequestBody defines body for CreateSubmission for multipart/form-data ContentType.
type CreateSubmissionMultipartRequestBody = SubmissionUpload

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /api/v1/access-key)
	RevokeAccessKey(ctx *echo.Context) error

	// (POST /api/v1/access-key)
	IssueAccessKey(ctx *echo.Context) error

	// (POST /api/v1/admin/datasets/import)
	ImportDatasets(ctx *echo.Context) error

	// (POST /api/v1/admin/private/publish)
	PublishPrivate(ctx *echo.Context) error

	// (POST /api/v1/admin/private/unpublish)
	UnpublishPrivate(ctx *echo.Context) error

	// (GET /api/v1/admin/submissions)
	ListAdminSubmissions(ctx *echo.Context) error

	// (POST /api/v1/admin/submissions/{id}/disqualify)
	DisqualifySubmission(ctx *echo.Context, id Uuid) error

	// (POST /api/v1/admin/submissions/{id}/retry)
	RetrySubmission(ctx *echo.Context, id Uuid) error

	// (GET /api/v1/contest)
	GetContest(ctx *echo.Context) error

	// (GET /api/v1/contest/events)
	StreamContest(ctx *echo.Context, params StreamContestParams) error

	// (GET /api/v1/datasets)
	GetDatasets(ctx *echo.Context) error

	// (GET /api/v1/datasets/{datasetId}/{artifact}/download)
	DownloadDataset(ctx *echo.Context, datasetId string, artifact DatasetKind) error

	// (GET /api/v1/healthz)
	GetHealth(ctx *echo.Context) error

	// (GET /api/v1/leaderboard)
	GetLeaderboard(ctx *echo.Context, params GetLeaderboardParams) error

	// (GET /api/v1/leaderboard/replay)
	GetLeaderboardReplay(ctx *echo.Context) error

	// (GET /api/v1/me)
	GetMe(ctx *echo.Context) error

	// (GET /api/v1/readyz)
	GetReady(ctx *echo.Context) error

	// (GET /api/v1/submissions)
	ListSubmissions(ctx *echo.Context) error

	// (POST /api/v1/submissions)
	CreateSubmission(ctx *echo.Context) error

	// (GET /api/v1/submissions/events)
	StreamSubmissions(ctx *echo.Context) error

	// (GET /api/v1/submissions/{id})
	GetSubmission(ctx *echo.Context, id Uuid) error

	// (GET /api/v1/submissions/{id}/source)
	GetSubmissionSource(ctx *echo.Context, id Uuid) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RevokeAccessKey converts echo context to params.
func (w *ServerInterfaceWrapper) RevokeAccessKey(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RevokeAccessKey(ctx)
	return err
}

// IssueAccessKey converts echo context to params.
func (w *ServerInterfaceWrapper) IssueAccessKey(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.IssueAccessKey(ctx)
	return err
}

// ImportDatasets converts echo context to params.
func (w *ServerInterfaceWrapper) ImportDatasets(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportDatasets(ctx)
	return err
}

// PublishPrivate converts echo context to params.
func (w *ServerInterfaceWrapper) PublishPrivate(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PublishPrivate(ctx)
	return err
}

// UnpublishPrivate converts echo context to params.
func (w *ServerInterfaceWrapper) UnpublishPrivate(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnpublishPrivate(ctx)
	return err
}

// ListAdminSubmissions converts echo context to params.
func (w *ServerInterfaceWrapper) ListAdminSubmissions(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAdminSubmissions(ctx)
	return err
}

// DisqualifySubmission converts echo context to params.
func (w *ServerInterfaceWrapper) DisqualifySubmission(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DisqualifySubmission(ctx, id)
	return err
}

// RetrySubmission converts echo context to params.
func (w *ServerInterfaceWrapper) RetrySubmission(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RetrySubmission(ctx, id)
	return err
}

// GetContest converts echo context to params.
func (w *ServerInterfaceWrapper) GetContest(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetContest(ctx)
	return err
}

// StreamContest converts echo context to params.
func (w *ServerInterfaceWrapper) StreamContest(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamContestParams
	// ------------- Optional query parameter "board" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "board", ctx.QueryParams(), &params.Board, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter board: %s", err))
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "language", ctx.QueryParams(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter language: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StreamContest(ctx, params)
	return err
}

// GetDatasets converts echo context to params.
func (w *ServerInterfaceWrapper) GetDatasets(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDatasets(ctx)
	return err
}

// DownloadDataset converts echo context to params.
func (w *ServerInterfaceWrapper) DownloadDataset(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "datasetId" -------------
	var datasetId string

	err = runtime.BindStyledParameterWithOptions("simple", "datasetId", ctx.Param("datasetId"), &datasetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter datasetId: %s", err))
	}

	// ------------- Path parameter "artifact" -------------
	var artifact DatasetKind

	err = runtime.BindStyledParameterWithOptions("simple", "artifact", ctx.Param("artifact"), &artifact, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter artifact: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DownloadDataset(ctx, datasetId, artifact)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetLeaderboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetLeaderboard(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams
	// ------------- Optional query parameter "board" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "board", ctx.QueryParams(), &params.Board, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter board: %s", err))
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "language", ctx.QueryParams(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter language: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLeaderboard(ctx, params)
	return err
}

// GetLeaderboardReplay converts echo context to params.
func (w *ServerInterfaceWrapper) GetLeaderboardReplay(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLeaderboardReplay(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// GetReady converts echo context to params.
func (w *ServerInterfaceWrapper) GetReady(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReady(ctx)
	return err
}

// ListSubmissions converts echo context to params.
func (w *ServerInterfaceWrapper) ListSubmissions(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSubmissions(ctx)
	return err
}

// CreateSubmission converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSubmission(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSubmission(ctx)
	return err
}

// StreamSubmissions converts echo context to params.
func (w *ServerInterfaceWrapper) StreamSubmissions(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StreamSubmissions(ctx)
	return err
}

// GetSubmission converts echo context to params.
func (w *ServerInterfaceWrapper) GetSubmission(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSubmission(ctx, id)
	return err
}

// GetSubmissionSource converts echo context to params.
func (w *ServerInterfaceWrapper) GetSubmissionSource(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSubmissionSource(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/api/v1/access-key", wrapper.RevokeAccessKey, options.OperationMiddlewares["revokeAccessKey"]...)
	router.POST(options.BaseURL+"/api/v1/access-key", wrapper.IssueAccessKey, options.OperationMiddlewares["issueAccessKey"]...)
	router.POST(options.BaseURL+"/api/v1/admin/datasets/import", wrapper.ImportDatasets, options.OperationMiddlewares["importDatasets"]...)
	router.POST(options.BaseURL+"/api/v1/admin/private/publish", wrapper.PublishPrivate, options.OperationMiddlewares["publishPrivate"]...)
	router.POST(options.BaseURL+"/api/v1/admin/private/unpublish", wrapper.UnpublishPrivate, options.OperationMiddlewares["unpublishPrivate"]...)
	router.GET(options.BaseURL+"/api/v1/admin/submissions", wrapper.ListAdminSubmissions, options.OperationMiddlewares["listAdminSubmissions"]...)
	router.POST(options.BaseURL+"/api/v1/admin/submissions/:id/disqualify", wrapper.DisqualifySubmission, options.OperationMiddlewares["disqualifySubmission"]...)
	router.POST(options.BaseURL+"/api/v1/admin/submissions/:id/retry", wrapper.RetrySubmission, options.OperationMiddlewares["retrySubmission"]...)
	router.GET(options.BaseURL+"/api/v1/contest", wrapper.GetContest, options.OperationMiddlewares["getContest"]...)
	router.GET(options.BaseURL+"/api/v1/contest/events", wrapper.StreamContest, options.OperationMiddlewares["streamContest"]...)
	router.GET(options.BaseURL+"/api/v1/datasets", wrapper.GetDatasets, options.OperationMiddlewares["getDatasets"]...)
	router.GET(options.BaseURL+"/api/v1/datasets/:datasetId/:artifact/download", wrapper.DownloadDataset, options.OperationMiddlewares["downloadDataset"]...)
	router.GET(options.BaseURL+"/api/v1/healthz", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/api/v1/leaderboard", wrapper.GetLeaderboard, options.OperationMiddlewares["getLeaderboard"]...)
	router.GET(options.BaseURL+"/api/v1/leaderboard/replay", wrapper.GetLeaderboardReplay, options.OperationMiddlewares["getLeaderboardReplay"]...)
	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.GET(options.BaseURL+"/api/v1/readyz", wrapper.GetReady, options.OperationMiddlewares["getReady"]...)
	router.GET(options.BaseURL+"/api/v1/submissions", wrapper.ListSubmissions, options.OperationMiddlewares["listSubmissions"]...)
	router.POST(options.BaseURL+"/api/v1/submissions", wrapper.CreateSubmission, options.OperationMiddlewares["createSubmission"]...)
	router.GET(options.BaseURL+"/api/v1/submissions/events", wrapper.StreamSubmissions, options.OperationMiddlewares["streamSubmissions"]...)
	router.GET(options.BaseURL+"/api/v1/submissions/:id", wrapper.GetSubmission, options.OperationMiddlewares["getSubmission"]...)
	router.GET(options.BaseURL+"/api/v1/submissions/:id/source", wrapper.GetSubmissionSource, options.OperationMiddlewares["getSubmissionSource"]...)

}
